INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('1', '001', 'Categories', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('2', '002', 'Compagnies', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('3', '003', 'Unité Supérieure 1', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('4', '004', 'Types point de vente', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('5', '005', 'Points de vente', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('6', '006', 'Unité Supérieure 2', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('7', '007', 'Entité de gestion', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('8', '008', 'Espace Users', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('9', '009', 'Initialisation Numéro Assuré', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('10', '010', 'Initialiser registres Product', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('11', '011', 'Initialiser registres Sinistres', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('12', '012', 'Clôture Production', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('13', '013', 'Clôture Encaissement', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('14', '014', 'Mot de Passe', 1);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('16', '016', 'Professions', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('15', '015', 'Qualités', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('17', '017', 'Villes', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('18', '018', 'Activités', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('19', '019', 'Assurés', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('20', '020', 'Conventions', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('21', '021', 'Statuts Socio-professionnels', 2);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('22', '022', 'Affaires Nouvelles', 52);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('23', '023', 'Avenants', 52);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('32', '032', 'Saisie', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('33', '033', 'Consultation', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('34', '034', 'Validation', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('35', '035', 'Echéancier Paiement', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('36', '036', 'Saisie Echéancier', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('37', '037', 'Validation Echéancier', 102);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('38', '038', 'Ouverture', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('39', '039', 'Affectation', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('40', '040', 'Suivi', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('41', '041', 'Consultation', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('42', '042', 'Consulation Evènement', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('43', '043', 'Règlement', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('44', '044', 'Encaissement', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('45', '045', 'Bordereaux Règlements Honoraires', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('46', '046', 'Intrances Judiciaires', 103);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('47', '047', 'Reporting', 104);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('48', '048', 'Compagnies', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('49', '049', 'Catégories', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('50', '050', 'Exclusions des Garanties', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('51', '051', 'Garanties Liées', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('52', '052', 'Politique Garantie', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('53', '053', 'Durées', 105);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('54', '054', 'Types de Quittances', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('55', '055', 'Fractionnement Prime', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('56', '056', 'Paramétrage des avenants', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('57', '057', 'Frais de gestion', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('58', '058', 'Accessoires', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('59', '059', 'Commission', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('60', '060', 'Paramétrage des zones', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('61', '061', 'Taxes', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('62', '062', 'Paramétrage Régions-Villes', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('63', '063', 'Référenciel Véhicules', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('64', '064', 'Genres Automobile', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('65', '065', 'Usages Automobile', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('66', '066', 'Sous Usage TPV', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('67', '067', 'Permis de conduire', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('68', '068', 'Modes de paiement', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('69', '069', 'Stock des Documents/Inte.', 106);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('24', '024', 'Annulation d Actes', 52);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('72', '025', 'Consultation', 52);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('73', '026', 'Vehicule', 52);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('74', '027', 'Affaires Nouvelles', 53);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('75', '028', 'Avenants', 53);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('76', '029', 'Consultation', 53);
INSERT INTO "options" ("id", "code", "designation", "menu_id") VALUES ('77', '030', 'Annulation d''actes', 53);
