name: Laravel Continuous Deployment

on:
  push:
    branches:
      - main  # Déclencher sur chaque push sur la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Version de PHP utilisée dans le projet
          extensions: mbstring, pdo, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          tools: composer

      - name: Install dependencies
        run: composer update

      - name: Run Laravel migrations
        run: php artisan migrate --force

      - name: Sync files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/u370313450/public_html/public_html/byfallchat"
